spring.application.name=walletApp
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/taskforce
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.open-in-view=false

#Spring security settings
spring.security.user.name=admin
spring.security.user.password=admin

